if($questId == null) then
	print("Not a valid quest id");
	return -1;
end;

$result = display_choices("You aren't doing this quest any more. Are you sure?", 
	array["Yes", "No"]);
	
if($result == 1) then
	display_message("Ok, back ya go!");
	return 0;
end;

$questCodex = global.property["ActiveQuestList"];

if $questCodex[$questId] == null then
	print($questId + " was not found.");
	return -1;
end;
	
$questCodex[$questId]["questStatus"] = "Abandoned";
execute_script("PopulateQuestLog");