if($quest_id  == null) then
	print("Not a valid quest id");
	return -1;
end;

$result = display_choices("You aren't doing this quest any more. Are you sure?", 
	array["Yes", "No"]);
	
if($result == 1) then
	display_message("Ok, back ya go!");
	return 0;
end;

$questCodex = global.property["ActiveQuestList"];

if $questCodex[$quest_id] == null then
	print($quest_id + " was not found.");
	return -1;
end;
	
$questCodex[$quest_id]["questStatus"] = "Abandoned";
execute_script("PopulateQuestLog");