if $quest_id == null then
	print("No valid quest_id");
	return -1;
end;

$locQuest = global.property["ActiveQuestList"][$quest_id];

if ($locQuest == null) then
	$questScriptName = get_quest_script($quest_id, "init");
	execute_script($questScriptName, true);
	return 0;
end;

if($locQuest["questStatus"] == "Completed") then
	display_message("You have already completed this quest! The creator should really put in a archive of old quests, huh.");
	return 0;
end;

