if $quest_id == null then
	print("No valid quest_id");
	return -1;
end;

$questScriptName = get_quest_script($quest_id, "end");
execute_script($questScriptName, true);

// first get the quest from the active quest list
$questCodex = global.property["ActiveQuestList"];

if $questCodex[$quest_id] == null then
	print($quest_id + " was not found.");
	return -1;
end;

$questCodex[$quest_id]["questStatus"] = "Completed";