// testing
print(widget["Quest2"]);

// first button
print(widget["Quest2"].element["0002"]);
//widget["Quest2"].element["0002"].visible = false;
widget["Quest2"].element["0002"].text = "Display a message";
widget["Quest2"].element["0002"].script = "DisplayAMessage";


//widget["Quest2"].element["0002"].text = "Updated in script";

 //widget["Quest2"].element["0004"]


//print(str(widget["Quest2"].element["0004"].currentvalue));